-- Supabase Row Level Security policies (generated by Dreamflow agent)

-- Enable RLS on all tables
alter table public.users enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.stories enable row level security;
alter table public.message_threads enable row level security;
alter table public.messages enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.studio_sessions enable row level security;
alter table public.opportunities enable row level security;
alter table public.opportunity_applications enable row level security;
alter table public.monetization_transactions enable row level security;
alter table public.notifications enable row level security;
alter table public.early_access_requests enable row level security;
alter table public.portfolio_items enable row level security;
alter table public.campaigns enable row level security;
alter table public.missions enable row level security;
alter table public.rewards enable row level security;
alter table public.user_campaign_memberships enable row level security;
alter table public.user_mission_progress enable row level security;
alter table public.user_rewards enable row level security;
alter table public.feature_policies enable row level security;
alter table public.kill_switches enable row level security;
alter table public.feature_policy_audit enable row level security;

-- USERS table: allow authenticated users to read their own row.
drop policy if exists users_select_own on public.users;
create policy users_select_own on public.users
  for select
  to authenticated
  using (id = auth.uid());

-- Users inserts/updates must be allowed for onboarding flows.
-- IMPORTANT: WITH CHECK(true) is required per Dreamflow guidance.
drop policy if exists users_insert_any on public.users;
create policy users_insert_any on public.users
  for insert
  to authenticated
  with check (true);

drop policy if exists users_update_any on public.users;
create policy users_update_any on public.users
  for update
  to authenticated
  using (id = auth.uid())
  with check (true);

-- Broad policies for the rest: authenticated users can do all operations.
-- NOTE: tighten these later for production.

-- IMPORTANT:
-- We intentionally avoid PL/pgSQL (DO $$ ... FOREACH ... EXECUTE format(...)) here.
-- Some runners (or manual "run selected query" flows) execute statements individually,
-- which would break on `FOREACH` / `EXECUTE format(...)`.
-- Keeping this section as plain SQL makes it robust and re-runnable.

drop policy if exists posts_all_authed on public.posts;
create policy posts_all_authed on public.posts for all to authenticated using (true) with check (true);

drop policy if exists comments_all_authed on public.comments;
create policy comments_all_authed on public.comments for all to authenticated using (true) with check (true);

drop policy if exists stories_all_authed on public.stories;
create policy stories_all_authed on public.stories for all to authenticated using (true) with check (true);

drop policy if exists message_threads_all_authed on public.message_threads;
create policy message_threads_all_authed on public.message_threads for all to authenticated using (true) with check (true);

drop policy if exists messages_all_authed on public.messages;
create policy messages_all_authed on public.messages for all to authenticated using (true) with check (true);

drop policy if exists groups_all_authed on public.groups;
create policy groups_all_authed on public.groups for all to authenticated using (true) with check (true);

drop policy if exists group_members_all_authed on public.group_members;
create policy group_members_all_authed on public.group_members for all to authenticated using (true) with check (true);

drop policy if exists studio_sessions_all_authed on public.studio_sessions;
create policy studio_sessions_all_authed on public.studio_sessions for all to authenticated using (true) with check (true);

drop policy if exists opportunities_all_authed on public.opportunities;
create policy opportunities_all_authed on public.opportunities for all to authenticated using (true) with check (true);

drop policy if exists opportunity_applications_all_authed on public.opportunity_applications;
create policy opportunity_applications_all_authed on public.opportunity_applications for all to authenticated using (true) with check (true);

drop policy if exists monetization_transactions_all_authed on public.monetization_transactions;
create policy monetization_transactions_all_authed on public.monetization_transactions for all to authenticated using (true) with check (true);

drop policy if exists notifications_all_authed on public.notifications;
create policy notifications_all_authed on public.notifications for all to authenticated using (true) with check (true);

drop policy if exists early_access_requests_all_authed on public.early_access_requests;
create policy early_access_requests_all_authed on public.early_access_requests for all to authenticated using (true) with check (true);

drop policy if exists portfolio_items_all_authed on public.portfolio_items;
create policy portfolio_items_all_authed on public.portfolio_items for all to authenticated using (true) with check (true);

drop policy if exists campaigns_all_authed on public.campaigns;
create policy campaigns_all_authed on public.campaigns for all to authenticated using (true) with check (true);

drop policy if exists missions_all_authed on public.missions;
create policy missions_all_authed on public.missions for all to authenticated using (true) with check (true);

drop policy if exists rewards_all_authed on public.rewards;
create policy rewards_all_authed on public.rewards for all to authenticated using (true) with check (true);

drop policy if exists user_campaign_memberships_all_authed on public.user_campaign_memberships;
create policy user_campaign_memberships_all_authed on public.user_campaign_memberships for all to authenticated using (true) with check (true);

drop policy if exists user_mission_progress_all_authed on public.user_mission_progress;
create policy user_mission_progress_all_authed on public.user_mission_progress for all to authenticated using (true) with check (true);

drop policy if exists user_rewards_all_authed on public.user_rewards;
create policy user_rewards_all_authed on public.user_rewards for all to authenticated using (true) with check (true);

drop policy if exists feature_policies_all_authed on public.feature_policies;
create policy feature_policies_all_authed on public.feature_policies for all to authenticated using (true) with check (true);

drop policy if exists kill_switches_all_authed on public.kill_switches;
create policy kill_switches_all_authed on public.kill_switches for all to authenticated using (true) with check (true);

drop policy if exists feature_policy_audit_all_authed on public.feature_policy_audit;
create policy feature_policy_audit_all_authed on public.feature_policy_audit for all to authenticated using (true) with check (true);
