-- Supabase database schema (generated by Dreamflow agent)
-- Apply via Dreamflow Supabase module migrations.

create extension if not exists pgcrypto;

-- Users
create table if not exists public.users (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  display_name text,
  avatar_url text,
  active_role text,
  roles jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Social / content
create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references public.users (id) on delete cascade,
  title text,
  body text,
  media_urls jsonb not null default '[]'::jsonb,
  like_count int not null default 0,
  comment_count int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts (id) on delete cascade,
  author_id uuid not null references public.users (id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stories (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references public.users (id) on delete cascade,
  title text,
  body text,
  media_urls jsonb not null default '[]'::jsonb,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Messaging
create table if not exists public.message_threads (
  id uuid primary key default gen_random_uuid(),
  created_by uuid references public.users (id) on delete set null,
  participant_ids jsonb not null default '[]'::jsonb,
  last_message_preview text,
  last_message_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.message_threads (id) on delete cascade,
  sender_id uuid not null references public.users (id) on delete cascade,
  body text,
  media_urls jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Groups
create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references public.users (id) on delete set null,
  name text not null,
  description text,
  member_count int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.group_members (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.groups (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,
  role text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (group_id, user_id)
);

-- Studio sessions (LiveKit)
create table if not exists public.studio_sessions (
  id uuid primary key default gen_random_uuid(),
  host_id uuid not null references public.users (id) on delete cascade,
  room_name text,
  status text,
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Opportunities / applications
create table if not exists public.opportunities (
  id uuid primary key default gen_random_uuid(),
  created_by uuid references public.users (id) on delete set null,
  title text not null,
  description text,
  status text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.opportunity_applications (
  id uuid primary key default gen_random_uuid(),
  opportunity_id uuid not null references public.opportunities (id) on delete cascade,
  applicant_id uuid not null references public.users (id) on delete cascade,
  status text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (opportunity_id, applicant_id)
);

-- Monetization
create table if not exists public.monetization_transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users (id) on delete set null,
  kind text,
  amount_cents int not null default 0,
  currency text not null default 'USD',
  provider text,
  provider_ref text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Notifications
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users (id) on delete cascade,
  title text,
  body text,
  kind text,
  is_read boolean not null default false,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Early access / onboarding
create table if not exists public.early_access_requests (
  id uuid primary key default gen_random_uuid(),
  email text,
  name text,
  status text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Portfolio
create table if not exists public.portfolio_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users (id) on delete cascade,
  title text,
  description text,
  links jsonb not null default '[]'::jsonb,
  media_urls jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Progression: campaigns, missions, rewards, progress
create table if not exists public.campaigns (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  status text,
  starts_at timestamptz,
  ends_at timestamptz,
  image_url text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.missions (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid references public.campaigns (id) on delete set null,
  title text not null,
  description text,
  status text,
  kind text,
  points int not null default 0,
  image_url text,
  rules jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rewards (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  kind text,
  image_url text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_campaign_memberships (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users (id) on delete cascade,
  campaign_id uuid not null references public.campaigns (id) on delete cascade,
  joined_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, campaign_id)
);

create table if not exists public.user_mission_progress (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users (id) on delete cascade,
  mission_id uuid not null references public.missions (id) on delete cascade,
  status text,
  progress jsonb not null default '{}'::jsonb,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, mission_id)
);

create table if not exists public.user_rewards (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users (id) on delete cascade,
  reward_id uuid not null references public.rewards (id) on delete cascade,
  granted_by uuid references public.users (id) on delete set null,
  granted_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, reward_id, granted_at)
);

-- Feature flags / policies (server-authoritative)
create table if not exists public.feature_policies (
  id uuid primary key default gen_random_uuid(),
  role_key text not null,
  policy jsonb not null,
  is_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (role_key)
);

create table if not exists public.kill_switches (
  id uuid primary key default gen_random_uuid(),
  key text not null,
  is_enabled boolean not null default false,
  reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (key)
);

create table if not exists public.feature_policy_audit (
  id uuid primary key default gen_random_uuid(),
  actor_user_id uuid references public.users (id) on delete set null,
  entity_type text not null,
  entity_key text not null,
  action text not null,
  before jsonb,
  after jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- RPC: stable DTO-like contract for the progression feature policy.
--
-- Shape:
-- {
--   "flags": {"progression_enabled": true, ...},
--   "loaded_at": "2026-01-01T00:00:00Z",
--   "source": "rpc"
-- }
--
-- Notes:
-- - Safe defaults are applied if there is no row for a role.
-- - Kill switches always merge in (even if the role policy row is disabled).
create or replace function public.get_feature_policy(role text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_flags jsonb := '{}'::jsonb;
  v_policy jsonb;
  v_policy_enabled boolean := true;
  v_key text;
  v_enabled boolean;
begin
  select fp.policy, fp.is_enabled
    into v_policy, v_policy_enabled
  from public.feature_policies fp
  where fp.role_key = role
  limit 1;

  if v_policy_enabled and v_policy is not null then
    v_flags := v_policy;
  end if;

  -- Baseline: if no configured policy exists, return a launch-friendly read posture.
  if v_flags = '{}'::jsonb then
    v_flags := jsonb_build_object(
      'progression_enabled', true,
      'missions_enabled', true,
      'campaigns_enabled', true,
      'redemptions_enabled', true,
      'profiles_progression_enabled', true
    );
  end if;

  -- Merge kill switches.
  for v_key, v_enabled in
    select ks.key, ks.is_enabled
    from public.kill_switches ks
  loop
    v_flags := jsonb_set(v_flags, array[v_key], to_jsonb(coalesce(v_enabled, false)), true);
  end loop;

  return jsonb_build_object(
    'flags', v_flags,
    'loaded_at', now(),
    'source', 'rpc'
  );
end;
$$;
